name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy files to EC2
      run: |
        rsync -avz --exclude='node_modules' --exclude='.git' -e "ssh -o StrictHostKeyChecking=no" . ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/

    - name: Set environment variables
      env:
        API_URL: ${{ secrets.API_URL }}
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          echo "export API_URL=${API_URL}" >> /home/ubuntu/.bashrc
          echo "API_URL=${API_URL}" > /home/ubuntu/.env
          source /home/ubuntu/.bashrc
        EOF

    - name: Install Docker (if not installed)
      run: |
        if ! command -v docker &> /dev/null
        then
          sudo apt update
          sudo apt install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
        fi

    - name: Add user to Docker group (if not already added)
      run: |
        if ! getent group docker | grep -q "\b${USER}\b"
        then
          sudo usermod -aG docker $USER
          newgrp docker <<EONG
          docker ps
          EONG
        fi

    - name: Run Docker Compose on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu
          sudo docker-compose down
          sudo docker-compose pull
          sudo docker-compose up -d
        EOF
