name: Deploy to EC2 and test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Backend Dependencies
      working-directory: backend
      run: npm install

    - name: Run Backend Tests
      working-directory: backend
      run: npm run test

  # deploy:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

  #   - name: Add SSH key
  #     uses: webfactory/ssh-agent@v0.5.3
  #     with:
  #       ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

  #   - name: Copy files to EC2
  #     run: |
  #       rsync -avz --exclude='node_modules' --exclude='.git' -e "ssh -o StrictHostKeyChecking=no" . ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/app/

  #   - name: Set environment variables
  #     env:
  #       API_URL: ${{ secrets.API_URL }}
  #     run: |
  #       ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
  #         sudo echo "export API_URL=${API_URL}" >> /home/ubuntu/.bashrc
  #         sudo echo "API_URL=${API_URL}" > /home/ubuntu/app/.env
  #         source /home/ubuntu/.bashrc
  #       EOF

  #   - name: Run Docker Compose on EC2
  #     run: |
  #       ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
  #         cd /home/ubuntu/app
  #         sudo docker-compose down
  #         sudo docker-compose up --build -d
  #       EOF
